### ISSUE TITLE
Изменить формат некоторых фоток

### ISSUE THREAD

**Issue by f4lz** [Bo4kaa/work_1#44]
У тебя уже есть фотки, но нужно их экспортировать в нужном формат. Почитай например на htmlacademy про то, какие фотки какого расширения должны быть (jpg, png, svg)

**Comment by Bo4kaa** [comment]
и как понять в каких фотках формат менять?

**Comment by f4lz** [comment]
> и как понять в каких фотках формат менять?

почитать в  интернете) Тут например htmlacademy
